/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigGuide: typeof import('./src/components/ConfigGuide.vue')['default']
    ConversiationTable: typeof import('./src/components/ConversiationTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Login: typeof import('./src/components/Login.vue')['default']
    MarkdwonText: typeof import('./src/components/MarkdwonText.vue')['default']
    MyBeautifulChat: typeof import('./src/components/MyBeautifulChat.vue')['default']
    MyConfig: typeof import('./src/components/MyConfig.vue')['default']
  }
}
